site_name: Zep - Fast, scalable building blocks for LLM apps
site_url: https://docs.getzep.com
site_description: Fast, scalable building blocks for chat history memory, vector search, data enrichment, and more..
copyright: Copyright &copy; 2023 - Zep Software, Inc.
repo_url: https://github.com/getzep/zep
edit_uri: https://github.com/getzep/docs.getzep.com/blob/main/docs/
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: posthog
  homepage: https://www.getzep.com
nav:
  - Home: index.md
  - Quick Start ⚡️: deployment/quickstart.md
  - SDKs and API:
      - sdk/index.md
      - Document Store: 
          - sdk/documents.md
      - Chat History:
          - sdk/chat_history/index.md
          - Users: sdk/chat_history/users.md
          - Sessions: sdk/chat_history/sessions.md
          - Memories: sdk/chat_history/memories.md
          - Search Chat History: sdk/chat_history/search.md
      - Enrichments: 
          - sdk/extractors.md
      - Frameworks:
          - LangChain 🦜⛓️: sdk/langchain.md
          - LlamaIndex 🦙: sdk/llamaindex.md
      - Examples:
          - sdk/examples.md
      - APIs:
          - Python SDK API: https://getzep.github.io/zep-python/zep_client/
          - JavaScript SDK API: https://getzep.github.io/zep-js/
          - REST API: https://getzep.github.io/zep/
  - Deployment:
      - deployment/index.md
      - Quick Start: deployment/quickstart.md
      - Web UI: deployment/webui.md
      - Production: deployment/production.md
      - Render: deployment/render.md
      - Kubernetes: deployment/kubernetes.md
  - Configuration:
      - deployment/config.md
      - Selecting Embedding Models: deployment/embeddings.md
      - Authentication: deployment/auth.md
      - LLM API Config: deployment/llm_config.md
      - Data Management: deployment/data.md

  - Support: support/index.md
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  features:
    - content.action.edit
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
  logo: images/zep-bot-square-50x50.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - abbr
  - def_list
  - tables
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - typeset
  - optimize
  - git-revision-date-localized:
      enable_creation_date: true
