site_name: Zep - A long-term memory store for LLM applications
repo_url: https://github.com/getzep/zep
site_url: https://docs.getzep.com
site_description: Zep stores, summarizes, embeds, indexes, and enriches LLM app / AI chatbot histories.
copyright: Copyright &copy; 2023 - Zep Software, Inc.
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: posthog
  homepage: https://www.getzep.com
nav:
  - Home: index.md
  - Quick Start ⚡️: deployment/quickstart.md
  - Langchain ❤️: sdk/langchain.md
  - SDKs and API:
      - sdk/index.md
      - Document Store: sdk/documents.md
      - Chat History: sdk/chat_history.md
      - Langchain ❤️: sdk/langchain.md
      - Examples: sdk/examples.md
      - Concepts: sdk/concepts.md
      - Extractors: sdk/extractors.md
      - Python SDK API: https://getzep.github.io/zep-python/zep_client/
      - JavaScript SDK API: https://getzep.github.io/zep-js/
      - REST API: https://getzep.github.io/zep/
  - Deployment:
        - deployment/index.md
        - Quick Start: deployment/quickstart.md
        - Production: deployment/production.md
        - Render: deployment/render.md
        - Kubernetes: deployment/kubernetes.md
  - Configuration:
      - deployment/config.md
      - Selecting Embedding Models: deployment/embeddings.md
      - Authentication: deployment/auth.md
      - OpenAI API Config: deployment/openai.md
      - Data Management: deployment/data.md

  - Support: support/index.md
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
  logo: images/zep-bot-square-50x50.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - admonition
  - abbr
  - def_list
  - tables
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
