name: docs-build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: write
jobs:
  deploy:
    environment: doc-build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y pngquant
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r docs/requirements.txt
      - run: pip install git+https://anything:${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force 
